spring:
  datasource:
    driver-class-name:
      org.mariadb.jdbc.Driver
  profiles:
    active: develop
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create
    show_sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
security:
  enabled: true