spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tangntalk?characterEncoding=UTF-8&serverTimezone=UTC
    username: tangntalk
    password: secret
  redis:
    host: localhost
    port: 6379
    password:
security:
  enabled: false
jwt:
  raw-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
