spring:
  datasource:
    driver-class-name:
      org.mariadb.jdbc.Driver
  profiles:
    active: develop
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
security:
  enabled: false
